spring:
  datasource:
    url: jdbc:mysql://avnadmin:REDACTED@mysql-1a7d050b-qd0420-4b53.l.aivencloud.com:15603/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: REDACTED
  jpa:
    hibernate:
      # ddl auto에 대해서 어떻게 설정? : create, create-drop, update
      # update : 개발환경에서는...
      # validate, none
      # 진짜 배울 때만...
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  # logging
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG