spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-1a7d050b-qd0420-4b53.l.aivencloud.com}:${DB_PORT:15603}/${DB_NAME:defaultdb}?ssl-mode=REQUIRED
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      # ddl auto에 대해서 어떻게 설정? : create, create-drop, update
      # update : 개발환경에서는...
      # validate, none
      # 진짜 배울 때만...
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  # logging
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG